### ISSUE TITLE
Add subject to Cloud Event

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/sources-for-knative#117]
As mentioned in the comment the cloud events `subject` is currently not set for vSphere events.

https://github.com/vmware-tanzu/sources-for-knative/blob/6826a547b9d7876f23e26149811fd6bdac038754/pkg/vsphere/adapter.go#L101

Since vSphere events can be arbitrary (Alerts, VM related events, 3rd party, etc.), i.e. there is not a standard/stable definition of `subject`, the question is whether `subject` can (should) be set on a vCenter cloud event. There are definitely valid use cases, e.g. setting the VM `moRef` for a `VmPoweredOnEvent` or host `moRef` for a `EnteredMaintenanceModeEvent`.

Since `moRef` is composed of a `type` and `value`, a composite key for `subject` might be useful, e.g. `VirtualMachine/vm-56`.

**Comment by vaikas** [comment]
Yea, so looking at the ManagedObjectReference, type/value seems reasonable. Though, I wonder if we're processing events from multiple vspheres if we need to prefix it with something else also to avoid collisions?

**Comment by embano1** [comment]
Wouldn't `source` tie the `moRef` to the concrete `vcenter` instance, i.e. composite of `source` and `subject` is unique?

**Comment by vaikas** [comment]
Probably, just wanted to jot it down while I was thinking about it :)

**Comment by embano1** [comment]
related: https://github.com/vmware-samples/vcenter-event-broker-appliance/issues/182#issuecomment-850380039

**Comment by embano1** [comment]
Closing with `wontfix` since there's currently no easy way to extract a well-defined "subject" from an arbitrary vSphere event.
