### ISSUE TITLE
Support event replay (at-least-once semantics)

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/sources-for-knative#120]
Currently there is no support for redelivering events in case of cloud events `send` fails after retries (no ACK), the vsphere source crashes/reboots, etc. Supporting `at-least-once` event delivery semantics would be desirable so that we don't skip/lose vsphere events in these scenarios.

A simple approach could be local file checkpointing (with optional strong persistence) to capture the last successfully ACK-ed event. E.g.  in VEBA we use this file structure:

```json
{
  "vCenter": "10.0.0.1",
  "lastEventUUID": "f8d71cb0-fd66-4e3b-aae1-b62d4576bf40",
  "lastEventKey": 26071,
  "lastEventType": "UserLogoutSessionEvent",
  "lastEventKeyTimestamp": "2020-10-13T08:05:36.792Z",
  "createdTimestamp": "2020-10-13T08:05:55.534638Z"
}
```

This file is read after startup and the event stream is started from `lastEventKeyTimestamp` (starting from key/offset is not supported in the public API). A time limit range can be set to have an upper bound for the starting point, e.g. `t.Now()-1h`.

Related: #119

**Comment by vaikas** [comment]
We added a kvstore with this very issue in mind:
https://github.com/vmware-tanzu/sources-for-knative/blob/master/pkg/vsphere/adapter.go#L61

That way we could use k8s configmap if we wanted to get the persistence from the adapter point of view.

**Comment by embano1** [comment]
```go
// ... Handy for things like sources
// that need to persist some state (checkpointing for example).
```

Oh, this is brilliant and exactly what we need here! I like it :)

**Comment by vaikas** [comment]
And here's a super hacky source demonstrating how one could use it:
https://github.com/vaikas/ftp/blob/master/cmd/source/watcher.go#L72
