### ISSUE TITLE
Github action to run some basic e2e testing on KinD

### ISSUE THREAD

**Issue by mattmoor** [vmware-tanzu/sources-for-knative#22]
Looks like antrea has figured this out here: https://github.com/vmware-tanzu/antrea/blob/ab7eb6395938c70c890f83c44a45793c2cda3cc3/.github/workflows/kind.yml#L27

**Comment by cppforlife** [comment]
here is simpler way to run kind on GH actions: https://github.com/k14s/kapp/blob/master/.github/workflows/test-gh.yml#L16-L19
