### ISSUE TITLE
Codecov vulnerability

### ISSUE THREAD

**Issue by embano1** [vmware-tanzu/sources-for-knative#237]
Not sure if we're affected (did we ger pinged?), but might be worth checking binaries/creds and rotate in any case: https://about.codecov.io/security-update/

See also: https://blog.dapr.io/posts/2021/04/16/daprs-response-to-codecovs-bash-uploader-breach/

Updated action: https://github.com/codecov/codecov-action/issues/281

**Comment by x448** [comment]
Projects using Go, like [fxamacker/cbor](https://github.com/fxamacker/cbor) avoided this problem for over a year by using [my GitHub Actions script](https://github.com/x448/workflows) (MIT license).

If a problem is ever discovered with my script, then you have the power to fix it without waiting for me.  All of the code is inside -- it doesn't download any code from a 3rd-party vendor to work.

**Comment by embano1** [comment]
@evankanderson are we good here in terms of countermeasures?
