### ISSUE TITLE
Use the schema generation tool to generate the schema for CRDs.

### ISSUE THREAD

**Issue by n3wscott** [vmware-tanzu/sources-for-knative#253]
What's the current pattern in Knative projects to create schemas?

_Originally posted by @embano1 in https://github.com/vmware-tanzu/sources-for-knative/pull/250#r640679469_

**Comment by embano1** [comment]
Interesting question which I thought you'd have an answer for me :)

**Comment by embano1** [comment]
Thx @n3wscott for bringing this up again. Looks like this is the way to go in Knative https://github.com/knative/serving/blob/main/hack/update-schemas.sh ?

**Comment by n3wscott** [comment]
There are two ways... The serving way which is in development and might become the new standard in knative, and the eventing way using a simple reflection tool that gets you close: https://github.com/knative/eventing/blob/main/cmd/schema/main.go
