### ISSUE TITLE
[BUG] What to do regarding Security Warnings

### ISSUE THREAD

**Issue by gabo1208** [vmware-tanzu/sources-for-knative#377]
**Describe the bug**
Right now we are having security warnings with one of our libs
![image](https://user-images.githubusercontent.com/4516177/154554884-574ef37a-4750-4393-a37b-b09c1cb1057b.png)

**To Reproduce**
Any PR has this right now

**Expected behavior**
All jobs to pass

**Additional context**
We should do any change or ignore it for now?

**Comment by gabo1208** [comment]
cc @embano1

**Comment by xtreme-sameer-vohra** [comment]
Thanks for flagging this @gabo1208 
Does `sources-for-knative` allow an arbitrary user to define URLs used with `go-retryablehttp` ? That would raise the exposure according to https://cwe.mitre.org/data/definitions/117.html

From a quick glance, I don't see an upstream issue/patch in https://github.com/hashicorp/go-retryablehttp so it might be worth raising this upstream.

**Comment by embano1** [comment]
It's a transitive dependency in `vendor/knative.dev/eventing/pkg/kncloudevents/message_sender.go`. Looks like we are not seeing this in other kn repos then?

**Comment by embano1** [comment]
Do we still have this issue @gabo1208 ?

**Comment by embano1** [comment]
Looks like we're good here. Closing this, let me know if you have concerns @gabo1208
