### ISSUE TITLE
`kn` plugin

### ISSUE THREAD

**Issue by mattmoor** [vmware-tanzu/sources-for-knative#60]
We should build and release a `kn` plugin for the VMware sources and bindings.

I'd propose a surface like:
1. `login`: create the `vsphere-credentials` Secret with the appropriate shape,
2. `vspheresource`(?): create the source from an address + credentials and sink,
3. `vspherebinding`(?): create the binding from an address + credentials and subject.

This should:
* Follow the [example](https://github.com/knative/client-contrib/tree/master/plugins/hello),
* Update our [samples](https://github.com/vmware-tanzu/sources-for-knative/tree/master/samples) to use the CLI,
 * Include [e2e tests](https://github.com/vmware-tanzu/sources-for-knative/blob/45e8646d6715b2894a64e566f5352aeb17c1f50b/.github/workflows/kind-e2e.yaml#L90) against KinD,
 * Get bundled into [our release](https://github.com/vmware-tanzu/sources-for-knative/blob/master/.github/workflows/release.yaml) ([example of goreleaser](https://github.com/google/ko/blob/master/.github/workflows/release.yml))

**Comment by fbiville** [comment]
I'm on it.

**Comment by fbiville** [comment]
Regarding Sources, does the CLI restrict sink references to only Service, Kn Service and Kn Broker or must it be generic (i.e. have `--sink-ref-api-version`, `--sink-ref-kind`, `--sink-ref-name` flags)?

**Comment by vaikas** [comment]
> Regarding Sources, does the CLI restrict sink references to only Service, Kn Service and Kn Broker or must it be generic (i.e. have `--sink-ref-api-version`, `--sink-ref-kind`, `--sink-ref-name` flags)?

I think it should be generic since the Source can target anything that's addressable, for example in addition to the Broker, it could also be a Channel, Sequence, Parallel, etc. So not sure it's worth it to special case those constructs, since we need to support the general case as well. My $.02 :)

**Comment by fbiville** [comment]
Thanks @vaikas, I'll update the corresponding PR accordingly.
