### ISSUE TITLE
Update to latest sdk-go, v2.0.0

### ISSUE THREAD

**Issue by n3wscott** [vmware-tanzu/sources-for-knative#62]
We need this repo updated too.

**Comment by mattmoor** [comment]
Is this done? https://github.com/vmware-tanzu/sources-for-knative/blob/a417b315d91208e8ff3337811546664f8021b08b/go.mod#L7

**Comment by mattmoor** [comment]
ping @n3wscott

**Comment by embano1** [comment]
are we good? 

`github.com/cloudevents/sdk-go/v2 v2.2.0`

**Comment by mattmoor** [comment]
yeah I think so
